CAEN digitizer SDK: cvt_V1724.c File Reference
cvt_V1724.c File Reference
V1724 VME board implementation.
#include <memory.h>
#include <string.h>
#include "cvt_V1724.h"
Functions
BOOL cvt_V1724_open (cvt_V1724_data *p_data, UINT16 base_address, long vme_handle, CVT_V17XX_TYPES type)
V1724 VME boards data initialization.
BOOL cvt_V1724_close (cvt_V1724_data *p_data)
V1724 VME boards closing and resource free.
BOOL cvt_V1724_read_data (cvt_V1724_data *p_data, UINT32 *p_ch_max_samples, UINT32 *p_num_events)
Reads data from the board's channels and stores to user buffer.
BOOL cvt_V1724_get_buffer_cache (cvt_V1724_data *p_data, UINT16 event_index, UINT8 ch_index, UINT16 *p_buff, UINT32 *p_buff_size, UINT8 *p_board_id, UINT32 *p_trigger_time_tag, UINT32 *p_event_counter)
Reads data cache from previous cvt_V1724_read_data data call.
BOOL cvt_V1724_set_trigger_mode (cvt_V1724_data *p_data, BOOL falling_edge_enable, BOOL ext_trigger_enable, BOOL sw_trigger_enable, UINT8 ch_trigger_enable_msk, BOOL trigger_overlap_enable, UINT32 post_trigger)
Setups the triggering parameters.
BOOL cvt_V1724_get_trigger_mode (cvt_V1724_data *p_data, BOOL *p_falling_edge_enable, BOOL *p_ext_trigger_enable, BOOL *p_sw_trigger_enable, UINT8 *p_ch_trigger_enable_msk, BOOL *p_trigger_overlap_enable, UINT32 *p_post_trigger)
Gets the trigger out settings.
BOOL cvt_V1724_start_acquisition (cvt_V1724_data *p_data, UINT8 ch_msk)
Starts the acquisition for the spcified channel mask.
BOOL cvt_V1724_stop_acquisition (cvt_V1724_data *p_data)
Stops the acquisition.
BOOL cvt_V1724_set_acquisition_mode (cvt_V1724_data *p_data, BOOL sample_enable, CVT_V1724_NUM_BLOCKS block_size, CVT_V1724_ACQ_CONTROL_ACQ_MODES acquisition_mode, BOOL count_all_trigger, UINT32 downsample_factor)
Setups the acquisition mode parameters.
BOOL cvt_V1724_get_acquisition_mode (cvt_V1724_data *p_data, BOOL *p_sample_enable, CVT_V1724_NUM_BLOCKS *p_block_size)
Gets the acquisition mode parameters.
BOOL cvt_V1724_get_acquisition_status (cvt_V1724_data *p_data, BOOL *p_is_MEB_not_empty, BOOL *p_is_MEB_full, BOOL *p_is_running, BOOL *p_some_event_ready, BOOL *p_event_full, BOOL *p_s_in)
Gets the acquisition status parameters.
BOOL cvt_V1724_get_buffer_samples (cvt_V1724_data *p_data, UINT16 *p_num_k_samples, CVT_V1724_NUM_BLOCKS *p_num_block_read)
Returns the maximum number of samples per events for each channel.
BOOL cvt_V1724_set_buffer_samples (cvt_V1724_data *p_data, UINT16 num_k_samples, CVT_V1724_NUM_BLOCKS *p_num_block_written)
Sets the maximum number of samples per events for each channel.
BOOL cvt_V1724_set_fp_trigger_out (cvt_V1724_data *p_data, BOOL ext_trigger_enable, BOOL sw_trigger_enable, UINT8 ch_trigger_enable_msk)
Setups the front panel triggering output parameters.
BOOL cvt_V1724_get_fp_trigger_out (cvt_V1724_data *p_data, BOOL *p_ext_trigger_enable, BOOL *p_sw_trigger_enable, UINT8 *p_ch_trigger_enable_msk)
Gets the front panel trigger output settings.
BOOL cvt_V1724_set_dither_enable (cvt_V1724_data *p_data, UINT8 ch_msk, BOOL dither_value)
Setups the channels' dithering feature (V1724/V1720 only).
BOOL cvt_V1724_get_dither_enable (cvt_V1724_data *p_data, UINT8 ch_index, BOOL *p_dither_value)
Gets the specified channel' dithering feature status (V1724/V1720 only).
BOOL cvt_V1724_set_adc_conf (cvt_V1724_data *p_data, UINT8 ch_msk, BOOL dither_value, BOOL clk_duty_stab_value, BOOL randomize_value)
Setups the channels' adc configuration (V1724/V1720 only).
BOOL cvt_V1724_get_adc_conf (cvt_V1724_data *p_data, UINT8 ch_index, BOOL *p_dither_value, BOOL *p_clk_duty_stab_value, BOOL *p_randomize_value)
Gets the specified channel' adc configuration (V1724/V1720 only).
BOOL cvt_V1724_adc_calib (cvt_V1724_data *p_data, UINT8 ch_msk)
Performs the specified ADCs' channels calibration (V1731/V1721 only).
BOOL cvt_V1724_adc_temp (cvt_V1724_data *p_data, UINT8 ch_msk, UINT32 *tempadc)
Reads the specified ADCs' channels temperature (V1751 only).
BOOL cvt_V1724_set_des_mode (cvt_V1724_data *p_data, BOOL is_des_mode)
Switchs to DES mode or normal mode (V1731 only).
BOOL cvt_V1724_set_interrupt (cvt_V1724_data *p_data, UINT8 level, UINT32 status_id, UINT16 event_number)
Setups interrupt parameters.
BOOL cvt_V1724_get_interrupt (cvt_V1724_data *p_data, UINT8 *p_level, UINT32 *p_status_id, UINT16 *p_event_number)
Gets interrupt parameters.
BOOL cvt_V1724_set_readout_mode (cvt_V1724_data *p_data, BOOL enable_bus_error, UINT32 BLT_event_number)
Setups data readout mode parameters.
BOOL cvt_V1724_get_readout_mode (cvt_V1724_data *p_data, BOOL *p_enable_bus_error, UINT32 *p_BLT_event_number)
Gets data readout mode parameters.
BOOL cvt_V1724_software_reset (cvt_V1724_data *p_data)
Performs a software reset.
BOOL cvt_V1724_data_clear (cvt_V1724_data *p_data)
Performs a data clear.
BOOL cvt_V1724_set_channel_offset (cvt_V1724_data *p_data, UINT8 ch_msk, UINT16 offset_value)
Sets channels' offset.
BOOL cvt_V1724_get_channel_offset (cvt_V1724_data *p_data, UINT8 ch_index, UINT16 *p_offset_value)
Sets specified channel' offset.
BOOL cvt_V1724_set_channel_trigger (cvt_V1724_data *p_data, UINT8 ch_msk, UINT32 trigger_threshold, UINT32 threshold_samples)
Sets channels' trigger parameters.
BOOL cvt_V1724_get_channel_trigger (cvt_V1724_data *p_data, UINT8 ch_index, UINT32 *p_trigger_threshold, UINT32 *p_threshold_samples)
Gets the specified channel' trigger parameters.
BOOL cvt_V1724_set_front_panel_IO (cvt_V1724_data *p_data, BOOL use_TTL, BOOL out_en, UINT8 dir_msk, CVT_V1724_FRONT_PANEL_IO_MODES mode)
Sets front panel's IO.
BOOL cvt_V1724_get_front_panel_IO (cvt_V1724_data *p_data, BOOL *p_use_TTL, BOOL *p_is_out_en, UINT8 *p_dir_msk, CVT_V1724_FRONT_PANEL_IO_MODES *p_mode)
Gets front panel's IO.
BOOL cvt_V1724_software_trigger (cvt_V1724_data *p_data)
Performs a software trigger.
BOOL cvt_V1724_get_channel_status (cvt_V1724_data *p_data, UINT8 ch_index, BOOL *p_is_dac_busy, BOOL *p_is_fifo_full, BOOL *p_is_fifo_empty, BOOL *p_is_block_remove_ok)
Gets information about board status.
BOOL cvt_V1724_get_system_info (cvt_V1724_data *p_data, UINT16 *p_firmware_rev, CVT_V1724_ROM_CONFIG *p_rom_config, BOOL *p_is_board_type_correct, BOOL *p_is_firmware_rev_correct)
Gets board's system information.
BOOL cvt_V1724_get_channel_info (cvt_V1724_data *p_data, UINT8 ch_index, UINT16 *p_firmware_rev)
Gets board's system information.
BOOL cvt_V1724_set_MCST_CBLT (cvt_V1724_data *p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters for this board.
BOOL cvt_V1724_get_MCST_CBLT (cvt_V1724_data *p_data, UINT8 *p_address, MCST_CBLT_board_pos *p_pos)
Gets MCST/CBLT parameters from board.
BOOL cvt_V1724_write_flash_page (cvt_V1724_data *p_data, const UINT8 *page_buff, UINT32 page_index)
Writes a page into board's flash.
BOOL cvt_V1724_read_flash_page (cvt_V1724_data *p_data, UINT8 *page_buff, UINT32 page_index)
Reads a page from board's flash.
BOOL cvt_V1724_erase_flash_page (cvt_V1724_data *p_data, UINT32 page_index)
Erases a board's flash page.
BOOL cvt_V1724_fw_upgrade (cvt_V1724_data *p_data, const UINT8 *data_buff, UINT32 data_size, CVT_V1724_FLASH_BANK flash_bank, BOOL(*call_back)(UINT32 written_bytes))
Performs a full flash upgrade onto specific bank (standard or backup).
BOOL cvt_V1724_pll_upgrade (cvt_V1724_data *p_data, const char *filename)
Loads PLL from file and stores into flash.
const char * cvt_V1724_SW_rev (void)
Returns the SDK software release.
Detailed Description
V1724 VME board implementation.
Author:
NDA
Version:
1.0
Date:
10/2006
Provides methods, properties and defines to handle V1724 VME boards
Definition in file cvt_V1724.c.
Function Documentation
BOOL cvt_V1724_adc_calib (cvt_V1724_data * p_data, UINT8 ch_msk)
Performs the specified ADCs' channels calibration (V1731/V1721 only).
Parameters:
p_data Pointer to board data
ch_msk The channel mask to calibrate
Returns:
TRUE: Procedure successfully executed
< CH 0 Configuration register index
< CH 1 Configuration register index
< CH 2 Configuration register index
< CH 3 Configuration register index
< CH 4 Configuration register index
< CH 5 Configuration register index
< CH 6 Configuration register index
< CH 7 Configuration register index
< CH 0 status register relative address
< CH 1 status register relative address
< CH 2 status register relative address
< CH 3 status register relative address
< CH 4 status register relative address
< CH 5 status register relative address
< CH 6 status register relative address
< CH 7 status register relative address
Definition at line 1689 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_delay(), cvt_read_reg(), cvt_set_bitmask_reg(), CVT_V1721, CVT_V1724_BROAD_ADC_CONF_INDEX, CVT_V1724_BROAD_CH_CTRL_INDEX, CVT_V1724_BROAD_CHCTRL_DES_MODE_MSK, CVT_V1724_CH0_ADC_CONF_INDEX, CVT_V1724_CH0_STATUS_INDEX, CVT_V1724_CH1_ADC_CONF_INDEX, CVT_V1724_CH1_STATUS_INDEX, CVT_V1724_CH2_ADC_CONF_INDEX, CVT_V1724_CH2_STATUS_INDEX, CVT_V1724_CH3_ADC_CONF_INDEX, CVT_V1724_CH3_STATUS_INDEX, CVT_V1724_CH4_ADC_CONF_INDEX, CVT_V1724_CH4_STATUS_INDEX, CVT_V1724_CH5_ADC_CONF_INDEX, CVT_V1724_CH5_STATUS_INDEX, CVT_V1724_CH6_ADC_CONF_INDEX, CVT_V1724_CH6_STATUS_INDEX, CVT_V1724_CH7_ADC_CONF_INDEX, CVT_V1724_CH7_STATUS_INDEX, CVT_V1724_CHADCCONF_CAL_MSK_2, CVT_V1724_CHSTS_CAL_RUN_MSK, cvt_V1724_data_clear(), CVT_V1724_MAX_CHANNEL, cvt_V1724_set_des_mode(), CVT_V1724_SW_SYNC_INDEX, CVT_V1731, CVT_V1751, cvt_write_reg(), cvt_V1724_data::m_common_data, and cvt_V1724_data::m_type.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_adc_temp (cvt_V1724_data * p_data, UINT8 ch_msk, UINT32 * tempadc)
Reads the specified ADCs' channels temperature (V1751 only).
Parameters:
p_data Pointer to board data
ch_msk The channel mask read temperature from
tampadc The caller allocated storage to hold channels' temperatures: it must be a CVT_V1724_MAX_CHANNEL UINT32 data array
Returns:
TRUE: Procedure successfully executed
< CH 0 Configuration register index
< CH 1 Configuration register index
< CH 2 Configuration register index
< CH 3 Configuration register index
< CH 4 Configuration register index
< CH 5 Configuration register index
< CH 6 Configuration register index
< CH 7 Configuration register index
Definition at line 1837 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_CH0_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH1_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH2_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH3_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH4_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH5_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH6_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH7_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_MAX_CHANNEL, CVT_V1751, cvt_V1724_data::m_common_data, and cvt_V1724_data::m_type.
BOOL cvt_V1724_close (cvt_V1724_data * p_data)
V1724 VME boards closing and resource free.
Provides specific handling for V1724 boards closing.
Parameters:
p_data Pointer to board data
Returns:
TRUE: board successfully closed
Note:
Must be called when done with any other board specific API.
Definition at line 359 of file cvt_V1724.c.
References cvt_board_close(), cvt_V1724_data::m_cache_sample_buffer, cvt_V1724_data::m_cache_sample_buffer_read_bytes, cvt_V1724_data::m_cache_sample_buffer_size, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_data_clear (cvt_V1724_data * p_data)
Performs a data clear.
Writes a dummy value into SW_CLEAR_REGISTER register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 2352 of file cvt_V1724.c.
References CVT_V1724_SW_CLEAR_INDEX, cvt_write_reg(), and cvt_V1724_data::m_common_data.
Referenced by cvt_V1724_adc_calib(), and cvt_V1724_set_des_mode().
BOOL cvt_V1724_erase_flash_page (cvt_V1724_data * p_data, UINT32 page_index)
Erases a board's flash page.
Parameters:
p_data Pointer to board data.
page_index The page index (0 based index) to be erased
Returns:
TRUE: Procedure successfully executed
Definition at line 3275 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V1724_FLASH_DATA_INDEX, CVT_V1724_FLASH_EN_INDEX, CVT_V1724_FLEN_EN_MSK, CVT_V1724_FOP_PAGE_ERASE, cvt_write_reg(), and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_fw_upgrade (cvt_V1724_data * p_data, const UINT8 * data_buff, UINT32 data_size, CVT_V1724_FLASH_BANK flash_bank, BOOL(*)(UINT32 written_bytes) call_back)
Performs a full flash upgrade onto specific bank (standard or backup).
Parameters:
p_data Pointer to board data.
data_buff The source data buffer
data_size The data_buff size (bytes)
flash_bank The flash bank to upgrade: must be a CVT_V1724_FLASH_BANK valid one
call_back End user call back function, called for each new page transferred: may be NULL: you can return FALSE to abort procedure
Returns:
TRUE: Procedure successfully executed
Definition at line 3336 of file cvt_V1724.c.
References cvt_swap_bits(), CVT_V1724_FB_BACKUP, CVT_V1724_FB_STANDARD, cvt_V1724_read_flash_page(), cvt_V1724_write_flash_page(), and V1724_FLASH_PAGE_SIZE.
BOOL cvt_V1724_get_acquisition_mode (cvt_V1724_data * p_data, BOOL * p_sample_enable, CVT_V1724_NUM_BLOCKS * p_block_size)
Gets the acquisition mode parameters.
Retrives the relevant parameters settings for the acquisition mode.
Parameters:
p_data Pointer to board data
p_sample_enable Sample acquisition mode: if disabled the acquisition mode is windowed
p_block_size Samples' number per block size foreach channel: it must be a valid CVT_V1724_NUM_BLOCKS identifier.
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_NUM_BLOCKS
Definition at line 1093 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_BROAD_CH_CTRL_INDEX, CVT_V1724_BROAD_CHCTRL_GATE_MODE_MSK, CVT_V1724_BROAD_NUM_BLOCK_INDEX, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_get_acquisition_status (cvt_V1724_data * p_data, BOOL * p_is_MEB_not_empty, BOOL * p_is_MEB_full, BOOL * p_is_running, BOOL * p_some_event_ready, BOOL * p_event_full, BOOL * p_s_in)
Gets the acquisition status parameters.
Retrives the relevant parameters for the acquisition status.
Parameters:
p_data Pointer to board data
p_is_MEB_not_empty This flag is set if MEB is not empty
p_is_MEB_full This flag is set if MEB is full
p_is_running This flag is set if acquisition is running
p_some_event_ready This flag is set if some event is ready
p_event_full This flag is set if event memory is full
p_s_in This flag shows the front panel' S-IN signal logical state
Returns:
TRUE: Procedure successfully executed
Definition at line 1122 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_ACQ_STATUS_INDEX, CVT_V1724_ACQSTS_EVENT_FULL_MSK, CVT_V1724_ACQSTS_EVENT_RDY_MSK, CVT_V1724_ACQSTS_MEB_FULL_MSK, CVT_V1724_ACQSTS_MEB_NOT_EMPTY_MSK, CVT_V1724_ACQSTS_RUN_MSK, CVT_V1724_ACQSTS_S_IN_MSK, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_get_adc_conf (cvt_V1724_data * p_data, UINT8 ch_index, BOOL * p_dither_value, BOOL * p_clk_duty_stab_value, BOOL * p_randomize_value)
Gets the specified channel' adc configuration (V1724/V1720 only).
Gets the dither, clock duty cycle stabilizer and output randomize features status for the specified channel.
Parameters:
p_data Pointer to board data
ch_index The channel index
p_dither_value If TRUE the dither feature is enabled, disable otherwise
p_clk_duty_stab_value If TRUE the clock duty cycle stabilizer feature is enabled, disable otherwise
p_randomize_value If TRUE the output randomized feature is enabled, disable otherwise
Returns:
TRUE: Procedure successfully executed
< CH 0 Configuration register index
< CH 1 Configuration register index
< CH 2 Configuration register index
< CH 3 Configuration register index
< CH 4 Configuration register index
< CH 5 Configuration register index
< CH 6 Configuration register index
< CH 7 Configuration register index
Definition at line 1628 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1720, CVT_V1724, CVT_V1724_CH0_ADC_CONF_INDEX, CVT_V1724_CH1_ADC_CONF_INDEX, CVT_V1724_CH2_ADC_CONF_INDEX, CVT_V1724_CH3_ADC_CONF_INDEX, CVT_V1724_CH4_ADC_CONF_INDEX, CVT_V1724_CH5_ADC_CONF_INDEX, CVT_V1724_CH6_ADC_CONF_INDEX, CVT_V1724_CH7_ADC_CONF_INDEX, CVT_V1724_CHADCCONF_CLK_DUTY_STAB_MSK, CVT_V1724_CHADCCONF_DITHER_MSK, CVT_V1724_CHADCCONF_RND_MSK, CVT_V1724_MAX_CHANNEL, CVT_V1740, cvt_V1724_data::m_common_data, and cvt_V1724_data::m_type.
BOOL cvt_V1724_get_buffer_cache (cvt_V1724_data * p_data, UINT16 event_index, UINT8 ch_index, UINT16 * p_buff, UINT32 * p_buff_size, UINT8 * p_board_id, UINT32 * p_trigger_time_tag, UINT32 * p_event_counter)
Reads data cache from previous cvt_V1724_read_data data call.
Call cvt_FIFO_BLT_read for Multiple Event Buffer and stores data into user buffer. If the returned data is just a V1724 not valid datum, this is discarded.
Parameters:
p_data Pointer to board data
event_index The event index from which retrive data
ch_index The channel index
p_buff The target buffer: caller allocated
p_buff_size The buffer size (16 bit word). On exit will holds the number of words really read.
p_board_id The board id stored into event
p_trigger_time_tag The trigger time tag stored into event
p_event_counter The counter stored into event
Returns:
TRUE: Procedure successfully executed, FALSE elsewhere (e.g. event or channel index not found)
See also:
cvt_V1724_read_data
< The board is V1724
< The board is V1720
< The board is V1721
< The board is V1731
< The board is V1740
< The board is V1751
Definition at line 497 of file cvt_V1724.c.
References CVT_V1720, CVT_V1721, CVT_V1724, CVT_V1724_MAX_CHANNEL, CVT_V1731, CVT_V1740, CVT_V1751, cvt_V1724_data::m_cache_sample_buffer, cvt_V1724_data::m_cache_sample_buffer_size, and cvt_V1724_data::m_type.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_get_buffer_samples (cvt_V1724_data * p_data, UINT16 * p_num_k_samples, CVT_V1724_NUM_BLOCKS * p_num_block_read)
Returns the maximum number of samples per events for each channel.
Parameters:
p_data Pointer to board data
p_num_k_samples The number of samples (as K blocks) per channel or per group in case of CVT_V1740
p_num_block_read The num block register value read (CVT_V1724_NUM_BLOCKS)
Returns:
TRUE: Procedure successfully executed
< The board is V1724
< The board is V1720
< The board is V1740
< The board is V1721
< The board is V1731
< The board is V1731
Definition at line 1164 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1720, CVT_V1721, CVT_V1724, CVT_V1724_BOARD_INFO_INDEX, CVT_V1724_BROAD_NUM_BLOCK_INDEX, CVT_V1724_GET_BRDINF_BLOCK_SIZE_KW, CVT_V1731, CVT_V1740, CVT_V1751, cvt_V1724_data::m_common_data, cvt_V1724_data::m_is_des_mode, and cvt_V1724_data::m_type.
BOOL cvt_V1724_get_channel_info (cvt_V1724_data * p_data, UINT8 ch_index, UINT16 * p_firmware_rev)
Gets board's system information.
Reads the firmware revision register and the serial number.
Parameters:
p_data Pointer to board data
ch_index The index of the channel to test.
p_firmware_rev The channel's firmare release (MSB major release, LSB minor release).
Returns:
TRUE: Procedure successfully executed
< CH 0 firmware revision register relative index
< CH 1 firmware revision register relative index
< CH 2 firmware revision register relative index
< CH 3 firmware revision register relative index
< CH 4 firmware revision register relative index
< CH 5 firmware revision register relative index
< CH 6 firmware revision register relative index
< CH 7 firmware revision register relative index
Definition at line 2996 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_CH0_FW_REV_INDEX, CVT_V1724_CH1_FW_REV_INDEX, CVT_V1724_CH2_FW_REV_INDEX, CVT_V1724_CH3_FW_REV_INDEX, CVT_V1724_CH4_FW_REV_INDEX, CVT_V1724_CH5_FW_REV_INDEX, CVT_V1724_CH6_FW_REV_INDEX, CVT_V1724_CH7_FW_REV_INDEX, CVT_V1724_MAX_CHANNEL, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_get_channel_offset (cvt_V1724_data * p_data, UINT8 ch_index, UINT16 * p_offset_value)
Sets specified channel' offset.
Retrives the offset value for the specified channel.
Parameters:
p_data Pointer to board data
ch_index The channel index
p_offset_value The channel' offset value.
Returns:
TRUE: Procedure successfully executed
< CH 0 DAC Data Configuration register index
< CH 1 DAC Data Configuration register index
< CH 2 DAC Data Configuration register index
< CH 3 DAC Data Configuration register index
< CH 4 DAC Data Configuration register index
< CH 5 DAC Data Configuration register index
< CH 6 DAC Data Configuration register index
< CH 7 DAC Data Configuration register index
Definition at line 2444 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_CH0_DAC_CONF_INDEX, CVT_V1724_CH1_DAC_CONF_INDEX, CVT_V1724_CH2_DAC_CONF_INDEX, CVT_V1724_CH3_DAC_CONF_INDEX, CVT_V1724_CH4_DAC_CONF_INDEX, CVT_V1724_CH5_DAC_CONF_INDEX, CVT_V1724_CH6_DAC_CONF_INDEX, CVT_V1724_CH7_DAC_CONF_INDEX, CVT_V1724_GET_CH_DAC_CONF, cvt_V1724_get_channel_status(), CVT_V1724_MAX_CHANNEL, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_get_channel_status (cvt_V1724_data * p_data, UINT8 ch_index, BOOL * p_is_dac_busy, BOOL * p_is_fifo_full, BOOL * p_is_fifo_empty, BOOL * p_is_block_remove_ok)
Gets information about board status.
Parameters:
p_data Pointer to board data.
ch_index The index of the channel to test.
p_is_dac_busy Returns the channel's DAC_BUSY flag status.
p_is_fifo_full Returns the channel's FIFO_FULL flag status.
p_is_fifo_empty Returns the channel's FIFO_EMPTY flag status.
p_is_block_remove_ok Returns the channel's BLOCK_REM_OK flag status.
Returns:
TRUE: Procedure successfully executed.
< CH 0 status register relative address
< CH 1 status register relative address
< CH 2 status register relative address
< CH 3 status register relative address
< CH 4 status register relative address
< CH 5 status register relative address
< CH 6 status register relative address
< CH 7 status register relative address
Definition at line 2728 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_CH0_STATUS_INDEX, CVT_V1724_CH1_STATUS_INDEX, CVT_V1724_CH2_STATUS_INDEX, CVT_V1724_CH3_STATUS_INDEX, CVT_V1724_CH4_STATUS_INDEX, CVT_V1724_CH5_STATUS_INDEX, CVT_V1724_CH6_STATUS_INDEX, CVT_V1724_CH7_STATUS_INDEX, CVT_V1724_CHSTS_BLOCK_REM_OK_MSK, CVT_V1724_CHSTS_DAC_BUSY_MSK, CVT_V1724_CHSTS_FIFO_EMPTY_MSK, CVT_V1724_CHSTS_FIFO_FULL_MSK, CVT_V1724_MAX_CHANNEL, and cvt_V1724_data::m_common_data.
Referenced by cvt_V1724_get_channel_offset(), and cvt_V1724_set_channel_offset().
BOOL cvt_V1724_get_channel_trigger (cvt_V1724_data * p_data, UINT8 ch_index, UINT32 * p_trigger_threshold, UINT32 * p_threshold_samples)
Gets the specified channel' trigger parameters.
Retrives the relevant trigger parameters for the specified channel.
Parameters:
p_data Pointer to board data
ch_index The channel index
p_trigger_threshold The value of the trigger threshold
p_threshold_samples The hysteresis on threshold comparison
Returns:
TRUE: Procedure successfully executed
< CH 0 Threshold register index
< CH 1 Threshold register index
< CH 2 Threshold register index
< CH 3 Threshold register index
< CH 4 Threshold register index
< CH 5 Threshold register index
< CH 6 Threshold register index
< CH 7 Threshold register index
< CH 0 Over/Under Threshold Samples register index
< CH 1 Over/Under Threshold Samples register index
< CH 2 Over/Under Threshold Samples register index
< CH 3 Over/Under Threshold Samples register index
< CH 4 Over/Under Threshold Samples register index
< CH 5 Over/Under Threshold Samples register index
< CH 6 Over/Under Threshold Samples register index
< CH 7 Over/Under Threshold Samples register index
Definition at line 2576 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_CH0_THRESHOLD_INDEX, CVT_V1724_CH0_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH1_THRESHOLD_INDEX, CVT_V1724_CH1_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH2_THRESHOLD_INDEX, CVT_V1724_CH2_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH3_THRESHOLD_INDEX, CVT_V1724_CH3_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH4_THRESHOLD_INDEX, CVT_V1724_CH4_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH5_THRESHOLD_INDEX, CVT_V1724_CH5_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH6_THRESHOLD_INDEX, CVT_V1724_CH6_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH7_THRESHOLD_INDEX, CVT_V1724_CH7_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_MAX_CHANNEL, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_get_dither_enable (cvt_V1724_data * p_data, UINT8 ch_index, BOOL * p_dither_value)
Gets the specified channel' dithering feature status (V1724/V1720 only).
Gets the dither feature status for the specified channel.
Parameters:
p_data Pointer to board data
ch_index The channel index
p_dither_value If TRUE the dither feature is enabled, disable otherwise
Returns:
TRUE: Procedure successfully executed
Deprecated:
Use cvt_V1724_get_adc_conf
< CH 0 Configuration register index
< CH 1 Configuration register index
< CH 2 Configuration register index
< CH 3 Configuration register index
< CH 4 Configuration register index
< CH 5 Configuration register index
< CH 6 Configuration register index
< CH 7 Configuration register index
Definition at line 1490 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1720, CVT_V1724, CVT_V1724_CH0_ADC_CONF_INDEX, CVT_V1724_CH1_ADC_CONF_INDEX, CVT_V1724_CH2_ADC_CONF_INDEX, CVT_V1724_CH3_ADC_CONF_INDEX, CVT_V1724_CH4_ADC_CONF_INDEX, CVT_V1724_CH5_ADC_CONF_INDEX, CVT_V1724_CH6_ADC_CONF_INDEX, CVT_V1724_CH7_ADC_CONF_INDEX, CVT_V1724_CHADCCONF_DITHER_MSK, CVT_V1724_MAX_CHANNEL, CVT_V1740, cvt_V1724_data::m_common_data, and cvt_V1724_data::m_type.
BOOL cvt_V1724_get_fp_trigger_out (cvt_V1724_data * p_data, BOOL * p_ext_trigger_enable, BOOL * p_sw_trigger_enable, UINT8 * p_ch_trigger_enable_msk)
Gets the front panel trigger output settings.
Retrives the relevant parameters setting for the front panel triggering mode.
Parameters:
p_data Pointer to board data
p_ext_trigger_enable External trigger status output enable.
p_sw_trigger_enable Software trigger status output enable.
p_ch_trigger_enable_msk Trigger output from channels thresholds comparison status.
Returns:
TRUE: Procedure successfully executed
< Enable CH 0 trigger bit
< Enable CH 1 trigger bit
< Enable CH 2 trigger bit
< Enable CH 3 trigger bit
< Enable CH 4 trigger bit
< Enable CH 5 trigger bit
< Enable CH 6 trigger bit
< Enable CH 7 trigger bit
Definition at line 1376 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_FP_TRIGGER_OUT_ENABLE_INDEX, CVT_V1724_FPTRGEN_CH0_MSK, CVT_V1724_FPTRGEN_CH1_MSK, CVT_V1724_FPTRGEN_CH2_MSK, CVT_V1724_FPTRGEN_CH3_MSK, CVT_V1724_FPTRGEN_CH4_MSK, CVT_V1724_FPTRGEN_CH5_MSK, CVT_V1724_FPTRGEN_CH6_MSK, CVT_V1724_FPTRGEN_CH7_MSK, CVT_V1724_FPTRGEN_EXT_MSK, CVT_V1724_FPTRGEN_SW_MSK, CVT_V1724_MAX_CHANNEL, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_get_front_panel_IO (cvt_V1724_data * p_data, BOOL * p_use_TTL, BOOL * p_is_out_en, UINT8 * p_dir_msk, CVT_V1724_FRONT_PANEL_IO_MODES * p_mode)
Gets front panel's IO.
Retrives the relevant parameters for the front panel's IO.
Parameters:
p_data Pointer to board data
p_use_TTL True if the external signals standard is TTL type
p_is_out_en True if the trigger output is enabled
p_dir_msk Gets the direction mask
p_mode Gets the operational mode
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_FRONT_PANEL_IO_MODES
Definition at line 2676 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_FPIO_CTRL_OUT_DIS_MSK, CVT_V1724_FPIO_CTRL_TTL_MSK, CVT_V1724_FRONT_PANEL_IO_CTRL_INDEX, CVT_V1724_GET_FPIO_CTRL_DIR, CVT_V1724_GET_FPIO_CTRL_MODE, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_get_interrupt (cvt_V1724_data * p_data, UINT8 * p_level, UINT32 * p_status_id, UINT16 * p_event_number)
Gets interrupt parameters.
Retrives the relevant parameters settings for interrupt usage.
Parameters:
p_data Pointer to board data
p_level The interrupt level.
p_status_id The interrupt stayus id (interupt vector).
p_event_number The number of events to get an interrupt (if 0 interrupt feature is disabled).
Returns:
TRUE: Procedure successfully executed
Definition at line 2221 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_GET_INT_LEVEL, CVT_V1724_INT_EVENT_NUM_INDEX, CVT_V1724_INT_STATUS_ID_INDEX, CVT_V1724_VME_CONTROL_INDEX, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_get_MCST_CBLT (cvt_V1724_data * p_data, UINT8 * p_address, MCST_CBLT_board_pos * p_pos)
Gets MCST/CBLT parameters from board.
Retrives the relevant parameters for MCST/CBLT usage.
Parameters:
p_data Pointer to board data.
p_address The MCST/CBLT address.
p_pos The board position into the MCST / CBLT chain: it must be a MCST_CBLT_board_pos identifier
Returns:
TRUE: Procedure successfully executed
See also:
MCST_CBLT_board_pos
Definition at line 3074 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_GET_MCST_CBLT_ADD, CVT_V1724_GET_MCST_CBLT_CTRL, CVT_V1724_MCST_CBLT_ADD_CTRL_INDEX, CVT_V1724_MCST_CBLT_CTRL_DISABLED_BOARD, CVT_V1724_MCST_CBLT_CTRL_FIRST_BOARD, CVT_V1724_MCST_CBLT_CTRL_LAST_BOARD, CVT_V1724_MCST_CBLT_CTRL_MID_BOARD, cvt_V1724_data::m_common_data, MCST_CBLT_board_disabled, MCST_CBLT_board_pos_first, MCST_CBLT_board_pos_last, and MCST_CBLT_board_pos_mid.
BOOL cvt_V1724_get_readout_mode (cvt_V1724_data * p_data, BOOL * p_enable_bus_error, UINT32 * p_BLT_event_number)
Gets data readout mode parameters.
Retrives the relevant parameters settings for data readout.
Parameters:
p_data Pointer to board data
*p_enable_bus_error Bus error status: if TRUE the module is enabled to generate a Bus error to finish a block transfer.
*p_BLT_event_number The number of events to readout foreach BLT cycle.
Returns:
TRUE: Procedure successfully executed
Definition at line 2307 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_BLT_EVENT_NUM_INDEX, CVT_V1724_VME_CONTROL_INDEX, CVT_V1724_VME_CTRL_BERR_ENABLE_MSK, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_get_system_info (cvt_V1724_data * p_data, UINT16 * p_firmware_rev, CVT_V1724_ROM_CONFIG * p_rom_config, BOOL * p_is_board_type_correct, BOOL * p_is_firmware_rev_correct)
Gets board's system information.
Reads the firmware revision register and the serial number.
Parameters:
p_data Pointer to board data
p_firmware_rev The firmare release (MSB major release, LSB minor release).
p_rom_config The ROM configuration.
p_is_board_type_correct Return TRUE if the cvt_V1724_data::m_type matches the CVT_V1724_ROM_CONFIG::m_board_id type
p_is_firmware_rev_correct Return TRUE if the CVT_V1724_FW_REV register value is greater or equal then minimum requested level for this tool's version CVT_V1724_MIN_FIRMARE_REV
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_MIN_FIRMARE_REV
Definition at line 2768 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1720, CVT_V1721, CVT_V1724, CVT_V1724_FW_REV_INDEX, CVT_V1724_MIN_FIRMARE_REV, CVT_V1724_ROM_BOARD_ID_0_INDEX, CVT_V1724_ROM_BOARD_ID_1_INDEX, CVT_V1724_ROM_BOARD_ID_2_INDEX, CVT_V1724_ROM_C_CODE_INDEX, CVT_V1724_ROM_CHKSUM_INDEX, CVT_V1724_ROM_CHKSUM_LEN_0_INDEX, CVT_V1724_ROM_CHKSUM_LEN_1_INDEX, CVT_V1724_ROM_CHKSUM_LEN_2_INDEX, CVT_V1724_ROM_CONST_0_INDEX, CVT_V1724_ROM_CONST_1_INDEX, CVT_V1724_ROM_CONST_2_INDEX, CVT_V1724_ROM_OUI_0_INDEX, CVT_V1724_ROM_OUI_1_INDEX, CVT_V1724_ROM_OUI_2_INDEX, CVT_V1724_ROM_R_CODE_INDEX, CVT_V1724_ROM_REVISION_0_INDEX, CVT_V1724_ROM_REVISION_1_INDEX, CVT_V1724_ROM_REVISION_2_INDEX, CVT_V1724_ROM_REVISION_3_INDEX, CVT_V1724_ROM_SERIAL_0_INDEX, CVT_V1724_ROM_SERIAL_1_INDEX, CVT_V1724_ROM_VCXO_TYPE_INDEX, CVT_V1724_ROM_VERSION_INDEX, CVT_V1731, CVT_V1740, CVT_V1751, CVT_V1724_ROM_CONFIG::m_board_id, CVT_V1724_ROM_CONFIG::m_c_code, CVT_V1724_ROM_CONFIG::m_chksum, CVT_V1724_ROM_CONFIG::m_chksum_len, cvt_V1724_data::m_common_data, CVT_V1724_ROM_CONFIG::m_const, CVT_V1724_ROM_CONFIG::m_OUI, CVT_V1724_ROM_CONFIG::m_r_code, CVT_V1724_ROM_CONFIG::m_revision, CVT_V1724_ROM_CONFIG::m_serial, cvt_V1724_data::m_type, CVT_V1724_ROM_CONFIG::m_VCXO_type, and CVT_V1724_ROM_CONFIG::m_version.
BOOL cvt_V1724_get_trigger_mode (cvt_V1724_data * p_data, BOOL * p_falling_edge_enable, BOOL * p_ext_trigger_enable, BOOL * p_sw_trigger_enable, UINT8 * p_ch_trigger_enable_msk, BOOL * p_trigger_overlap_enable, UINT32 * p_post_trigger)
Gets the trigger out settings.
Retrives the relevant parameters setting for the triggering mode.
Parameters:
p_data Pointer to board data
p_falling_edge_enable Triggering on falling edge status
p_ext_trigger_enable External trigger status.
p_sw_trigger_enable Software trigger status.
p_ch_trigger_enable_msk Trigger from channels thresholds comparison status. If bit i of the mask is setted, the channel i feature is setted.
p_trigger_overlap_enable Trigger overlap feature status.
p_post_trigger Amount of post trigger samples status
Returns:
TRUE: Procedure successfully executed
< Enable CH 0 trigger bit
< Enable CH 1 trigger bit
< Enable CH 2 trigger bit
< Enable CH 3 trigger bit
< Enable CH 4 trigger bit
< Enable CH 5 trigger bit
< Enable CH 6 trigger bit
< Enable CH 7 trigger bit
Definition at line 842 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_BROAD_CH_CTRL_INDEX, CVT_V1724_BROAD_CHCTRL_TRG_OUT_THR_MSK, CVT_V1724_BROAD_CHCTRL_TRG_OVERLAP_MSK, CVT_V1724_MAX_CHANNEL, CVT_V1724_POST_TRIG_INDEX, CVT_V1724_TRGEN_CH0_MSK, CVT_V1724_TRGEN_CH1_MSK, CVT_V1724_TRGEN_CH2_MSK, CVT_V1724_TRGEN_CH3_MSK, CVT_V1724_TRGEN_CH4_MSK, CVT_V1724_TRGEN_CH5_MSK, CVT_V1724_TRGEN_CH6_MSK, CVT_V1724_TRGEN_CH7_MSK, CVT_V1724_TRGEN_EXT_MSK, CVT_V1724_TRGEN_SW_MSK, CVT_V1724_TRIGGER_SRC_ENABLE_INDEX, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_open (cvt_V1724_data * p_data, UINT16 base_address, long vme_handle, CVT_V17XX_TYPES type)
V1724 VME boards data initialization.
Provides specific handling for V1724 boards opening.
Parameters:
p_data Pointer to board data
base_address The board base address (MSW)
vme_handle The VME handle
type The board type : it must be a CVT_V17XX_TYPES value
Returns:
TRUE: board successfully opened
Note:
Must be called before any other board specific API.
See also:
CVT_V17XX_TYPES
< The board is V1724
< The board is V1721
< The board is V1731
< The board is V1720
< The board is V1740
< The board is V1751
< The board is V1724
< The board is V1720
< The board is V1740
< The board is V1721
< The board is V1731
< The board is V1751
< The board is V1731
< The board is V1751
Definition at line 252 of file cvt_V1724.c.
References cvt_board_open(), cvt_read_reg(), CVT_V1720, CVT_V1721, CVT_V1724, CVT_V1724_BOARD_INFO_INDEX, CVT_V1724_BROAD_CH_CTRL_INDEX, CVT_V1724_BROAD_CHCTRL_DES_MODE_MSK, CVT_V1724_GET_BRDINF_BLOCK_SIZE_KW, CVT_V1724_MAX_CHANNEL, CVT_V1724_NBLK_1024, cvt_V1724_set_MCST_CBLT(), CVT_V1731, CVT_V1740, CVT_V1751, cvt_V1724_data::m_cache_sample_buffer, cvt_V1724_data::m_cache_sample_buffer_read_bytes, cvt_V1724_data::m_cache_sample_buffer_size, cvt_V1724_data::m_common_data, cvt_V1724_data::m_is_des_mode, cvt_V1724_data::m_type, and cvt_board_data::set_MCST_CBLT.
BOOL cvt_V1724_pll_upgrade (cvt_V1724_data * p_data, const char * filename)
Loads PLL from file and stores into flash.
Parameters:
p_data Pointer to board data.
filename The source file
Returns:
TRUE: Procedure successfully executed
Definition at line 3394 of file cvt_V1724.c.
References CVT_V1724_PLL_FLASH_PAGE, CVT_V1724_RELOAD_CONFIG_INDEX, cvt_V1724_write_flash_page(), cvt_write_reg(), cvt_V1724_data::m_common_data, and V1724_FLASH_PAGE_SIZE.
cvt_V1724_read_data (cvt_V1724_data * p_data, UINT32 * p_ch_max_samples, UINT32 * p_num_events)
Reads data from the board's channels and stores to user buffer.
Calling cvt_V1724_read_data will cache the channels' data into internal buffer Then call cvt_V1724_get_buffer_cache to get cached data
Parameters:
p_data Pointer to board data
p_ch_max_samples returns the maximum number of samples per channel read for each event
p_num_events returns the number of events read
Returns:
TRUE: Procedure successfully executed
See also:
cvt_V1724_get_buffer_cache
< The board is V1724
< The board is V1720
< The board is V1721
< The board is V1731
< The board is V1740
< The board is V1751
Definition at line 395 of file cvt_V1724.c.
References cvt_FIFO_BLT_read(), cvt_read_reg(), CVT_V1720, CVT_V1721, CVT_V1724, CVT_V1724_EVENT_STORED_INDEX, CVT_V1724_IS_HEADER_TAG, CVT_V1724_MAX_BLT_EVENT_NUM, CVT_V1724_OUT_BUFFER_ADD, CVT_V1724_OUT_BUFFER_AM, CVT_V1724_OUT_BUFFER_DATA_SIZE, CVT_V1731, CVT_V1740, CVT_V1751, cvt_V1724_data::m_cache_sample_buffer, cvt_V1724_data::m_cache_sample_buffer_read_bytes, cvt_V1724_data::m_cache_sample_buffer_size, cvt_V1724_data::m_common_data, and cvt_V1724_data::m_type.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_read_flash_page (cvt_V1724_data * p_data, UINT8 * page_buff, UINT32 page_index)
Reads a page from board's flash.
Parameters:
p_data Pointer to board data.
page_buff The target page buffer: page_buff size must be V1724_FLASH_PAGE_SIZE and allocated by the caller
page_index The page index (0 based index) to be read
Returns:
TRUE: Procedure successfully executed
Definition at line 3187 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_read_reg(), cvt_set_bitmask_reg(), CVT_V1724_FLASH_DATA_INDEX, CVT_V1724_FLASH_EN_INDEX, CVT_V1724_FLEN_EN_MSK, CVT_V1724_FOP_PAGE_READ, cvt_write_reg(), cvt_V1724_data::m_common_data, and V1724_FLASH_PAGE_SIZE.
Referenced by cvt_V1724_fw_upgrade().
BOOL cvt_V1724_set_acquisition_mode (cvt_V1724_data * p_data, BOOL sample_enable, CVT_V1724_NUM_BLOCKS block_size, CVT_V1724_ACQ_CONTROL_ACQ_MODES acquisition_mode, BOOL count_all_trigger, UINT32 downsample_factor)
Setups the acquisition mode parameters.
Setups the relevant parameters for the acquisition mode.
Parameters:
p_data Pointer to board data
sample_enable Enable/Disable the sample acquisition mode: if disabled the acquisition mode is windowed
block_size Setup the samples' number per block size foreach channel: it must be a valid CVT_V1724_NUM_BLOCKS identifier.
acquisition_mode Setups the acquisition mode
count_all_trigger Set to TRUE if you want to count all triggers (accepted and not)
downsample_factor If != 0 the download factor will be setted and enabled , disabled otherwise
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_NUM_BLOCKS
< 1024 blocks
< 512 blocks
< 256 blocks
< 128 blocks
< 64 blocks
< 32 blocks
< 16 blocks
< 8 blocks
< 4 blocks
< 2 blocks
< 1 block
Definition at line 987 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V1724_ACQ_CONTROL_INDEX, CVT_V1724_ACQCTRL_ACQ_MODE_MSK, CVT_V1724_ACQCTRL_DOWNSAMPLE_MSK, CVT_V1724_ACQCTRL_EVENT_COUNTER_ALL_MSK, CVT_V1724_BROAD_CH_CLEAR_CTRL_INDEX, CVT_V1724_BROAD_CH_SET_CTRL_INDEX, CVT_V1724_BROAD_CHCTRL_GATE_MODE_MSK, CVT_V1724_BROAD_NUM_BLOCK_INDEX, CVT_V1724_DOWNSAMPLE_FACT_INDEX, CVT_V1724_NBLK_1, CVT_V1724_NBLK_1024, CVT_V1724_NBLK_128, CVT_V1724_NBLK_16, CVT_V1724_NBLK_2, CVT_V1724_NBLK_256, CVT_V1724_NBLK_32, CVT_V1724_NBLK_4, CVT_V1724_NBLK_512, CVT_V1724_NBLK_64, CVT_V1724_NBLK_8, CVT_V1724_SET_ACQCTRL_ACQ_MODE, cvt_write_reg(), and cvt_V1724_data::m_common_data.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_set_adc_conf (cvt_V1724_data * p_data, UINT8 ch_msk, BOOL dither_value, BOOL clk_duty_stab_value, BOOL randomize_value)
Setups the channels' adc configuration (V1724/V1720 only).
Enables/Disables the dither, clock duty cycle stabilizer and output randomize features for each channel specified with ch_msk.
Parameters:
p_data Pointer to board data
ch_msk The channel mask
dither_value Set to TRUE to enable the dither channels in the mask, FALSE to disable
clk_duty_stab_value Set to TRUE to enable the clock duty cycle stabilizer feature, FALSE to disable
randomize_value Set to TRUE to enable the output randomized feature, FALSE to disable
Returns:
TRUE: Procedure successfully executed
< CH 0 Configuration register index
< CH 1 Configuration register index
< CH 2 Configuration register index
< CH 3 Configuration register index
< CH 4 Configuration register index
< CH 5 Configuration register index
< CH 6 Configuration register index
< CH 7 Configuration register index
Definition at line 1545 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V1720, CVT_V1724, CVT_V1724_CH0_ADC_CONF_INDEX, CVT_V1724_CH1_ADC_CONF_INDEX, CVT_V1724_CH2_ADC_CONF_INDEX, CVT_V1724_CH3_ADC_CONF_INDEX, CVT_V1724_CH4_ADC_CONF_INDEX, CVT_V1724_CH5_ADC_CONF_INDEX, CVT_V1724_CH6_ADC_CONF_INDEX, CVT_V1724_CH7_ADC_CONF_INDEX, CVT_V1724_CHADCCONF_CLK_DUTY_STAB_MSK, CVT_V1724_CHADCCONF_DITHER_MSK, CVT_V1724_CHADCCONF_RND_MSK, CVT_V1724_MAX_CHANNEL, CVT_V1740, cvt_V1724_data::m_common_data, and cvt_V1724_data::m_type.
BOOL cvt_V1724_set_buffer_samples (cvt_V1724_data * p_data, UINT16 num_k_samples, CVT_V1724_NUM_BLOCKS * p_num_block_written)
Sets the maximum number of samples per events for each channel.
Parameters:
p_data Pointer to board data
num_k_samples The number of samples (as K blocks: valid values are power of 2 multiples) per channel or per group in case of CVT_V1740
p_num_block_written The num block register value written (CVT_V1724_NUM_BLOCKS)
Returns:
TRUE: Procedure successfully executed
< The board is V1724
< The board is V1720
< The board is V1740
< The board is V1721
< The board is V1731
< The board is V1751
Definition at line 1229 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1720, CVT_V1721, CVT_V1724, CVT_V1724_BOARD_INFO_INDEX, CVT_V1724_BROAD_NUM_BLOCK_INDEX, CVT_V1724_GET_BRDINF_BLOCK_SIZE_KW, CVT_V1724_NBLK_1024, CVT_V1731, CVT_V1740, CVT_V1751, cvt_write_reg(), cvt_V1724_data::m_common_data, cvt_V1724_data::m_is_des_mode, and cvt_V1724_data::m_type.
BOOL cvt_V1724_set_channel_offset (cvt_V1724_data * p_data, UINT8 ch_msk, UINT16 offset_value)
Sets channels' offset.
Sets the offset value for each channel specified with ch_msk.
Parameters:
p_data Pointer to board data
ch_msk The channel mask
offset_value The offset value to be applied to specified channels.
Returns:
TRUE: Procedure successfully executed
< CH 0 DAC Data Configuration register index
< CH 1 DAC Data Configuration register index
< CH 2 DAC Data Configuration register index
< CH 3 DAC Data Configuration register index
< CH 4 DAC Data Configuration register index
< CH 5 DAC Data Configuration register index
< CH 6 DAC Data Configuration register index
< CH 7 DAC Data Configuration register index
Definition at line 2368 of file cvt_V1724.c.
References CVT_V1724_CH0_DAC_CONF_INDEX, CVT_V1724_CH1_DAC_CONF_INDEX, CVT_V1724_CH2_DAC_CONF_INDEX, CVT_V1724_CH3_DAC_CONF_INDEX, CVT_V1724_CH4_DAC_CONF_INDEX, CVT_V1724_CH5_DAC_CONF_INDEX, CVT_V1724_CH6_DAC_CONF_INDEX, CVT_V1724_CH7_DAC_CONF_INDEX, CVT_V1724_CHDAC_SET_A_MSK, CVT_V1724_CHDAC_SET_B_MSK, cvt_V1724_get_channel_status(), CVT_V1724_MAX_CHANNEL, CVT_V1724_SET_CH_DAC_CONF, cvt_write_reg(), and cvt_V1724_data::m_common_data.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_set_channel_trigger (cvt_V1724_data * p_data, UINT8 ch_msk, UINT32 trigger_threshold, UINT32 threshold_samples)
Sets channels' trigger parameters.
Sets the relevant trigger parameters for each channel specified with ch_msk.
Parameters:
p_data Pointer to board data
ch_msk The channel mask
trigger_threshold The value of the trigger threshold
threshold_samples The hysteresis on threshold comparison
Returns:
TRUE: Procedure successfully executed
< CH 0 Threshold register index
< CH 1 Threshold register index
< CH 2 Threshold register index
< CH 3 Threshold register index
< CH 4 Threshold register index
< CH 5 Threshold register index
< CH 6 Threshold register index
< CH 7 Threshold register index
< CH 0 Over/Under Threshold Samples register index
< CH 1 Over/Under Threshold Samples register index
< CH 2 Over/Under Threshold Samples register index
< CH 3 Over/Under Threshold Samples register index
< CH 4 Over/Under Threshold Samples register index
< CH 5 Over/Under Threshold Samples register index
< CH 6 Over/Under Threshold Samples register index
< CH 7 Over/Under Threshold Samples register index
Definition at line 2508 of file cvt_V1724.c.
References CVT_V1724_CH0_THRESHOLD_INDEX, CVT_V1724_CH0_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH1_THRESHOLD_INDEX, CVT_V1724_CH1_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH2_THRESHOLD_INDEX, CVT_V1724_CH2_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH3_THRESHOLD_INDEX, CVT_V1724_CH3_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH4_THRESHOLD_INDEX, CVT_V1724_CH4_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH5_THRESHOLD_INDEX, CVT_V1724_CH5_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH6_THRESHOLD_INDEX, CVT_V1724_CH6_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH7_THRESHOLD_INDEX, CVT_V1724_CH7_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_MAX_CHANNEL, cvt_write_reg(), and cvt_V1724_data::m_common_data.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_set_des_mode (cvt_V1724_data * p_data, BOOL is_des_mode)
Switchs to DES mode or normal mode (V1731 only).
Performs the correct procedure to switch to DES mode (4 channels) or normal (8 channels) mode
Parameters:
p_data Pointer to board data
is_des_mode If TRUE the des mode is setted
Returns:
TRUE: Procedure successfully executed
Remarks:
!!! WARNING !!! Odd channel's input signal must be disconnected and acquisition setting will be modified
Definition at line 1889 of file cvt_V1724.c.
References cvt_delay(), CVT_V1724_ACQCTRL_ACQ_MODE_REGISTER_CTRL, cvt_V1724_adc_calib(), CVT_V1724_BROAD_CH_CLEAR_CTRL_INDEX, CVT_V1724_BROAD_CH_SET_CTRL_INDEX, CVT_V1724_BROAD_CHCTRL_DES_MODE_MSK, cvt_V1724_data_clear(), cvt_V1724_get_buffer_cache(), CVT_V1724_MAX_CHANNEL, CVT_V1724_NBLK_1024, cvt_V1724_read_data(), cvt_V1724_set_acquisition_mode(), cvt_V1724_set_channel_offset(), cvt_V1724_set_channel_trigger(), cvt_V1724_set_readout_mode(), cvt_V1724_set_trigger_mode(), cvt_V1724_software_trigger(), cvt_V1724_start_acquisition(), cvt_V1724_stop_acquisition(), CVT_V1731, CVT_V1751, cvt_write_reg(), cvt_V1724_data::m_common_data, cvt_V1724_data::m_is_des_mode, and cvt_V1724_data::m_type.
Referenced by cvt_V1724_adc_calib().
BOOL cvt_V1724_set_dither_enable (cvt_V1724_data * p_data, UINT8 ch_msk, BOOL dither_value)
Setups the channels' dithering feature (V1724/V1720 only).
Enables/Disables the dither feature for each channel specified with ch_msk.
Parameters:
p_data Pointer to board data
ch_msk The channel mask
dither_value Set to TRUE to enable the dither channels in the mask, FALSE to disable
Returns:
TRUE: Procedure successfully executed
Deprecated:
Use cvt_V1724_set_adc_conf
< CH 0 Configuration register index
< CH 1 Configuration register index
< CH 2 Configuration register index
< CH 3 Configuration register index
< CH 4 Configuration register index
< CH 5 Configuration register index
< CH 6 Configuration register index
< CH 7 Configuration register index
Definition at line 1423 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V1720, CVT_V1724, CVT_V1724_CH0_ADC_CONF_INDEX, CVT_V1724_CH1_ADC_CONF_INDEX, CVT_V1724_CH2_ADC_CONF_INDEX, CVT_V1724_CH3_ADC_CONF_INDEX, CVT_V1724_CH4_ADC_CONF_INDEX, CVT_V1724_CH5_ADC_CONF_INDEX, CVT_V1724_CH6_ADC_CONF_INDEX, CVT_V1724_CH7_ADC_CONF_INDEX, CVT_V1724_CHADCCONF_DITHER_MSK, CVT_V1724_MAX_CHANNEL, CVT_V1740, cvt_V1724_data::m_common_data, and cvt_V1724_data::m_type.
BOOL cvt_V1724_set_fp_trigger_out (cvt_V1724_data * p_data, BOOL ext_trigger_enable, BOOL sw_trigger_enable, UINT8 ch_trigger_enable_msk)
Setups the front panel triggering output parameters.
Setups the relevant parameters for the front panel triggering mode.
Parameters:
p_data Pointer to board data
ext_trigger_enable Enable/Disable the external trigger output.
sw_trigger_enable Enable/Disable the software trigger output.
ch_trigger_enable_msk Enable/Disable trigger output from channels thresholds comparison
Returns:
TRUE: Procedure successfully executed
< Enable CH 0 trigger bit
< Enable CH 1 trigger bit
< Enable CH 2 trigger bit
< Enable CH 3 trigger bit
< Enable CH 4 trigger bit
< Enable CH 5 trigger bit
< Enable CH 6 trigger bit
< Enable CH 7 trigger bit
Definition at line 1307 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V1724_FP_TRIGGER_OUT_ENABLE_INDEX, CVT_V1724_FPTRGEN_CH0_MSK, CVT_V1724_FPTRGEN_CH1_MSK, CVT_V1724_FPTRGEN_CH2_MSK, CVT_V1724_FPTRGEN_CH3_MSK, CVT_V1724_FPTRGEN_CH4_MSK, CVT_V1724_FPTRGEN_CH5_MSK, CVT_V1724_FPTRGEN_CH6_MSK, CVT_V1724_FPTRGEN_CH7_MSK, CVT_V1724_FPTRGEN_EXT_MSK, CVT_V1724_FPTRGEN_SW_MSK, CVT_V1724_MAX_CHANNEL, and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_set_front_panel_IO (cvt_V1724_data * p_data, BOOL use_TTL, BOOL out_en, UINT8 dir_msk, CVT_V1724_FRONT_PANEL_IO_MODES mode)
Sets front panel's IO.
Sets the relevant parameters for the front panel's IO.
Parameters:
p_data Pointer to board data
use_TTL If set, the external signals standard is TTL type, elsewhere NIM type is assumed
out_en If setted enables the trigger output
dir_msk Set direction mask
mode Set the operational mode
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_FRONT_PANEL_IO_MODES
< General purpose IO
< Programmed IO
< Pattern mode
Definition at line 2632 of file cvt_V1724.c.
References CVT_V1724_FPIO_CTRL_OUT_DIS_MSK, CVT_V1724_FPIO_CTRL_TTL_MSK, CVT_V1724_FPIO_MODES_GPIO, CVT_V1724_FPIO_MODES_PATTERN, CVT_V1724_FPIO_MODES_PROGIO, CVT_V1724_FRONT_PANEL_IO_CTRL_INDEX, CVT_V1724_SET_FPIO_CTRL_DIR, CVT_V1724_SET_FPIO_CTRL_MODE, cvt_write_reg(), and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_set_interrupt (cvt_V1724_data * p_data, UINT8 level, UINT32 status_id, UINT16 event_number)
Setups interrupt parameters.
Setups the relevant parameters for interrupt usage.
Parameters:
p_data Pointer to board data
level The interrupt level.
status_id The interrupt status id (interrupt vector).
event_number The number of events to get an interrupt (setting 0 interrupt feature is disabled).
Returns:
TRUE: Procedure successfully executed
Definition at line 2170 of file cvt_V1724.c.
References cvt_read_reg(), CVT_V1724_INT_EVENT_NUM_INDEX, CVT_V1724_INT_STATUS_ID_INDEX, CVT_V1724_SET_INT_LEVEL, CVT_V1724_VME_CONTROL_INDEX, cvt_write_reg(), and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_set_MCST_CBLT (cvt_V1724_data * p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters for this board.
Setups the relevant parameters for MCST/CBLT usage.
Parameters:
p_data Pointer to board data.
address The MCST/CBLT address.
pos The board position into the MCST / CBLT chain: it must be a MCST_CBLT_board_pos identifier
Returns:
TRUE: Procedure successfully executed
See also:
MCST_CBLT_board_pos
Definition at line 3035 of file cvt_V1724.c.
References CVT_V1724_MCST_CBLT_ADD_CTRL_INDEX, CVT_V1724_MCST_CBLT_CTRL_DISABLED_BOARD, CVT_V1724_MCST_CBLT_CTRL_FIRST_BOARD, CVT_V1724_MCST_CBLT_CTRL_LAST_BOARD, CVT_V1724_MCST_CBLT_CTRL_MID_BOARD, CVT_V1724_SET_MCST_CBLT_ADD, CVT_V1724_SET_MCST_CBLT_CTRL, cvt_write_reg(), cvt_V1724_data::m_common_data, MCST_CBLT_board_disabled, MCST_CBLT_board_pos_first, MCST_CBLT_board_pos_last, and MCST_CBLT_board_pos_mid.
Referenced by cvt_V1724_open().
BOOL cvt_V1724_set_readout_mode (cvt_V1724_data * p_data, BOOL enable_bus_error, UINT32 BLT_event_number)
Setups data readout mode parameters.
Setups the relevant parameters for data readout.
Parameters:
p_data Pointer to board data
enable_bus_error Enable bus error: the module is enabled to generate a Bus error to finish a block transfer.
BLT_event_number The number of events to readout foreach BLT cycle.
Returns:
TRUE: Procedure successfully executed
Definition at line 2261 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V1724_BLT_EVENT_NUM_INDEX, CVT_V1724_VME_CONTROL_INDEX, CVT_V1724_VME_CTRL_BERR_ENABLE_MSK, cvt_write_reg(), and cvt_V1724_data::m_common_data.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_set_trigger_mode (cvt_V1724_data * p_data, BOOL falling_edge_enable, BOOL ext_trigger_enable, BOOL sw_trigger_enable, UINT8 ch_trigger_enable_msk, BOOL trigger_overlap_enable, UINT32 post_trigger)
Setups the triggering parameters.
Setups the relevant parameters for the triggering mode.
Parameters:
p_data Pointer to board data
falling_edge_enable Enable/Disable triggering on falling edge
ext_trigger_enable Enable/Disable the external trigger.
sw_trigger_enable Enable/Disable the software trigger.
ch_trigger_enable_msk Enable/Disable trigger from channels thresholds comparison. If bit i of the mask is setted, the channel i feature is setted.
trigger_overlap_enable Enable/Disable the trigger overlap feature.
post_trigger The amount of post trigger samples
Returns:
TRUE: Procedure successfully executed
< Enable CH 0 trigger bit
< Enable CH 1 trigger bit
< Enable CH 2 trigger bit
< Enable CH 3 trigger bit
< Enable CH 4 trigger bit
< Enable CH 5 trigger bit
< Enable CH 6 trigger bit
< Enable CH 7 trigger bit
Definition at line 728 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_set_bitmask_reg(), CVT_V1724_BROAD_CH_CLEAR_CTRL_INDEX, CVT_V1724_BROAD_CH_SET_CTRL_INDEX, CVT_V1724_BROAD_CHCTRL_TRG_OUT_THR_MSK, CVT_V1724_BROAD_CHCTRL_TRG_OVERLAP_MSK, CVT_V1724_MAX_CHANNEL, CVT_V1724_POST_TRIG_INDEX, CVT_V1724_TRGEN_CH0_MSK, CVT_V1724_TRGEN_CH1_MSK, CVT_V1724_TRGEN_CH2_MSK, CVT_V1724_TRGEN_CH3_MSK, CVT_V1724_TRGEN_CH4_MSK, CVT_V1724_TRGEN_CH5_MSK, CVT_V1724_TRGEN_CH6_MSK, CVT_V1724_TRGEN_CH7_MSK, CVT_V1724_TRGEN_EXT_MSK, CVT_V1724_TRGEN_SW_MSK, CVT_V1724_TRIGGER_SRC_ENABLE_INDEX, cvt_write_reg(), and cvt_V1724_data::m_common_data.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_software_reset (cvt_V1724_data * p_data)
Performs a software reset.
Writes a dummy value into SW_RESET_REGISTER register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 2336 of file cvt_V1724.c.
References CVT_V1724_SW_RESET_INDEX, cvt_write_reg(), and cvt_V1724_data::m_common_data.
BOOL cvt_V1724_software_trigger (cvt_V1724_data * p_data)
Performs a software trigger.
Sends a software trigger. Software triggers must be enabled
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
See also:
cvt_V1724_set_trigger_mode
Definition at line 2710 of file cvt_V1724.c.
References CVT_V1724_SW_TRIGGER_INDEX, cvt_write_reg(), and cvt_V1724_data::m_common_data.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_start_acquisition (cvt_V1724_data * p_data, UINT8 ch_msk)
Starts the acquisition for the spcified channel mask.
Parameters:
p_data Pointer to board data
ch_msk The mask of enabled channels
Returns:
TRUE: Procedure successfully executed
< The board is V1724
< The board is V1720
< The board is V1721
< The board is V1740
< The board is V1721
< The board is V1751
Definition at line 911 of file cvt_V1724.c.
References cvt_set_bitmask_reg(), CVT_V1720, CVT_V1721, CVT_V1724, CVT_V1724_ACQ_CONTROL_INDEX, CVT_V1724_ACQCTRL_START_MSK, CVT_V1724_CH_ENABLE_INDEX, CVT_V1731, CVT_V1740, CVT_V1751, cvt_write_reg(), cvt_V1724_data::m_common_data, cvt_V1724_data::m_is_des_mode, and cvt_V1724_data::m_type.
Referenced by cvt_V1724_set_des_mode().
BOOL cvt_V1724_stop_acquisition (cvt_V1724_data * p_data)
Stops the acquisition.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Definition at line 970 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), CVT_V1724_ACQ_CONTROL_INDEX, CVT_V1724_ACQCTRL_START_MSK, and cvt_V1724_data::m_common_data.
Referenced by cvt_V1724_set_des_mode().
const char * cvt_V1724_SW_rev (void)
Returns the SDK software release.
Returns:
const char*: The SDK revision string
Definition at line 3494 of file cvt_V1724.c.
BOOL cvt_V1724_write_flash_page (cvt_V1724_data * p_data, const UINT8 * page_buff, UINT32 page_index)
Writes a page into board's flash.
Parameters:
p_data Pointer to board data.
page_buff The source page buffer: page_buff size must be V1724_FLASH_PAGE_SIZE bytes
page_index The page index (0 based index) to be written
Returns:
TRUE: Procedure successfully executed
Definition at line 3110 of file cvt_V1724.c.
References cvt_clear_bitmask_reg(), cvt_delay(), cvt_set_bitmask_reg(), CVT_V1724_FLASH_DATA_INDEX, CVT_V1724_FLASH_EN_INDEX, CVT_V1724_FLEN_EN_MSK, CVT_V1724_FOP_PAGE_PROG_TH_BUF1, cvt_write_reg(), cvt_V1724_data::m_common_data, and V1724_FLASH_PAGE_SIZE.
Referenced by cvt_V1724_fw_upgrade(), and cvt_V1724_pll_upgrade().